// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteConhecimentoDb.Models;

#nullable disable

namespace TesteConhecimentoDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250603113300_SeedPacotes")]
    partial class SeedPacotes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TesteConhecimentoDb.Models.Atividade", b =>
                {
                    b.Property<int>("CodAtv")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAtv"));

                    b.Property<string>("DescAtv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Vagas")
                        .HasColumnType("int");

                    b.HasKey("CodAtv");

                    b.ToTable("Atividades");
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.AxParticipanteAtividade", b =>
                {
                    b.Property<int>("CodPar")
                        .HasColumnType("int");

                    b.Property<int>("CodAtv")
                        .HasColumnType("int");

                    b.HasKey("CodPar", "CodAtv");

                    b.HasIndex("CodAtv");

                    b.ToTable("AxParticipanteAtividades");
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.AxParticipantePacote", b =>
                {
                    b.Property<int>("CodPar")
                        .HasColumnType("int");

                    b.Property<int>("CodPacote")
                        .HasColumnType("int");

                    b.HasKey("CodPar", "CodPacote");

                    b.HasIndex("CodPacote");

                    b.ToTable("AxParticipantePacotes");
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.Pacote", b =>
                {
                    b.Property<int>("CodPacote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPacote"));

                    b.Property<DateTime>("DataViradaPreco")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CodPacote");

                    b.ToTable("Pacotes");

                    b.HasData(
                        new
                        {
                            CodPacote = 1,
                            DataViradaPreco = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Gold",
                            Preco = 100.00m
                        },
                        new
                        {
                            CodPacote = 2,
                            DataViradaPreco = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Descricao = "Platinum",
                            Preco = 150.00m
                        });
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.Participante", b =>
                {
                    b.Property<int>("CodPar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodPar"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodPar");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.AxParticipanteAtividade", b =>
                {
                    b.HasOne("TesteConhecimentoDb.Models.Atividade", "Atividade")
                        .WithMany("AxParticipanteAtividades")
                        .HasForeignKey("CodAtv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteConhecimentoDb.Models.Participante", "Participante")
                        .WithMany("AxParticipanteAtividades")
                        .HasForeignKey("CodPar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.AxParticipantePacote", b =>
                {
                    b.HasOne("TesteConhecimentoDb.Models.Pacote", "Pacote")
                        .WithMany("AxParticipantePacotes")
                        .HasForeignKey("CodPacote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TesteConhecimentoDb.Models.Participante", "Participante")
                        .WithMany("AxParticipantePacotes")
                        .HasForeignKey("CodPar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pacote");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.Atividade", b =>
                {
                    b.Navigation("AxParticipanteAtividades");
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.Pacote", b =>
                {
                    b.Navigation("AxParticipantePacotes");
                });

            modelBuilder.Entity("TesteConhecimentoDb.Models.Participante", b =>
                {
                    b.Navigation("AxParticipanteAtividades");

                    b.Navigation("AxParticipantePacotes");
                });
#pragma warning restore 612, 618
        }
    }
}
